### ISSUE TITLE
How use localized day, months names?

### ISSUE THREAD

**Issue by gibson** [czukowski/I18n_Plural#24]
I try some methods and cant use it, but in distr files it has

**Comment by czukowski** [comment]
The Kohana branch has [Date::format()](https://github.com/czukowski/I18n_Plural/blob/3.3/master/classes/I18n/Date.php#L94) method for formatted date output, so you could use just that with the format string that works for you.

The 'raw' access to those string is quite simple as well. The date formatting class uses [this method](https://github.com/czukowski/I18n_Plural/blob/3.3/master/classes/I18n/Date/Format.php#L160) to retrieve the translations for week days, months, etc. You can see that it gets the whole array using the `___()` function and returns one item with the specified index.

Example:

    ___('date.months', 'gen') // this will get you all month names in genitive case.
